# Generated by Django 3.1.7 on 2021-03-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='spotting_urination',
        ),
        migrations.RemoveField(
            model_name='train',
            name='spotting_urination',
        ),
    ]
