# Generated by Django 3.1.7 on 2021-03-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_auto_20210330_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='dischromic_patches',
        ),
        migrations.RemoveField(
            model_name='test',
            name='foul_smell_of_urine',
        ),
        migrations.RemoveField(
            model_name='test',
            name='toxic_look_typhos',
        ),
        migrations.RemoveField(
            model_name='train',
            name='dischromic_patches',
        ),
        migrations.RemoveField(
            model_name='train',
            name='foul_smell_of_urine',
        ),
        migrations.RemoveField(
            model_name='train',
            name='toxic_look_typhos',
        ),
    ]
