# Generated by Django 3.1.7 on 2021-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_auto_20210412_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease_with_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=150)),
                ('one', models.CharField(max_length=250)),
                ('two', models.CharField(max_length=250)),
                ('three', models.CharField(max_length=250)),
                ('detail', models.CharField(max_length=250)),
            ],
        ),
    ]
