# Generated by Django 3.1.7 on 2021-04-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0009_disease_with_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_with_details',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
    ]
