# Generated by Django 3.1.7 on 2021-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0010_auto_20210413_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='detail',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='pre_one',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='pre_three',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='pre_two',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
