# Generated by Django 3.1.7 on 2021-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_auto_20210413_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disease_with_details',
        ),
        migrations.AddField(
            model_name='disease',
            name='pre_four',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
