# Generated by Django 3.1.7 on 2021-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0012_auto_20210413_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=250)),
                ('specialisation', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
