# Generated by Django 3.1.7 on 2021-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0014_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='doctors',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicines',
            name='doctors_two',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
