# Generated by Django 3.1.7 on 2021-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0017_auto_20210415_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_login',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor_login',
            name='password',
            field=models.EmailField(max_length=200),
        ),
    ]
