# Generated by Django 3.1.7 on 2021-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0018_auto_20210415_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='image_four',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicines',
            name='image_one',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicines',
            name='image_three',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicines',
            name='image_two',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
