# Generated by Django 3.1.7 on 2021-04-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0021_auto_20210416_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor_login',
            new_name='doctorlogin',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
