# Generated by Django 3.1.7 on 2021-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0022_auto_20210416_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
