# Generated by Django 3.1.7 on 2021-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0024_appointment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
