# Generated by Django 3.1.7 on 2021-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0025_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='',max_length=20),
            preserve_default=False,
        ),
    ]
