# Generated by Django 3.1.7 on 2021-04-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0027_auto_20210416_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='age',
            new_name='patient_age',
        ),
    ]
