# Generated by Django 3.1.7 on 2021-04-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0028_auto_20210416_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
