# Generated by Django 3.1.7 on 2021-04-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0030_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_age',
        ),
    ]
