# Generated by Django 3.1.7 on 2021-04-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0031_remove_appointment_patient_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='Appoint',
        ),
    ]
