# Generated by Django 3.1.7 on 2021-04-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0032_auto_20210416_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='message',
        ),
    ]
