# Generated by Django 3.1.7 on 2021-04-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0033_remove_appoint_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='age',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='message',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
