# Generated by Django 3.1.7 on 2021-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0035_auto_20210416_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='age',
            field=models.IntegerField(),
        ),
    ]
