# Generated by Django 3.1.7 on 2021-04-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0036_auto_20210416_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='age',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
