from django.db import models

# Create your models here.
class train(models.Model): 
    itching=models.IntegerField(null=True)
    skin_rash=models.IntegerField(null=True)
    nodal_skin_eruptions=models.IntegerField(null=True)
    continuous_sneezing=models.IntegerField(null=True)
    shivering=models.IntegerField(null=True)
    chills=models.IntegerField(null=True)
    joint_pain=models.IntegerField(null=True)
    stomach_pain=models.IntegerField(null=True)
    acidity=models.IntegerField(null=True)
    ulcers_on_tongue=models.IntegerField(null=True)
    muscle_wasting=models.IntegerField(null=True)
    vomiting=models.IntegerField(null=True)
    burning_micturition=models.IntegerField(null=True)
    #spotting_urination=models.IntegerField()
    fatigue=models.IntegerField(null=True)
    weight_gain=models.IntegerField(null=True)
    anxiety=models.IntegerField(null=True)
    cold_hands_and_feets=models.IntegerField(null=True)
    mood_swings=models.IntegerField(null=True)
    weight_loss=models.IntegerField(null=True)
    restlessness=models.IntegerField(null=True)
    lethargy=models.IntegerField(null=True)
    patches_in_throat=models.IntegerField(null=True)
    irregular_sugar_level=models.IntegerField(null=True)
    cough=models.IntegerField(null=True)
    high_fever=models.IntegerField(null=True)
    high_fever=models.IntegerField(null=True)
    sunken_eyes=models.IntegerField(null=True)
    breathlessness=models.IntegerField(null=True)
    sweating=models.IntegerField(null=True)
    dehydration=models.IntegerField(null=True)
    indigestion=models.IntegerField(null=True)
    headache=models.IntegerField(null=True)
    yellowish_skin=models.IntegerField(null=True)
    dark_urine=models.IntegerField(null=True)
    nausea=models.IntegerField(null=True)
    loss_of_appetite=models.IntegerField(null=True)
    pain_behind_the_eyes=models.IntegerField(null=True)
    back_pain=models.IntegerField(null=True)
    constipation=models.IntegerField(null=True)
    abdominal_pain=models.IntegerField(null=True)
    diarrhoea=models.IntegerField(null=True)
    mild_fever=models.IntegerField(null=True)
    mild_fever=models.IntegerField(null=True)
    yellowing_of_eyes=models.IntegerField(null=True)
    acute_liver_failure=models.IntegerField(null=True)
    fluid_overload=models.IntegerField(null=True)
    swelling_of_stomach=models.IntegerField(null=True)
    swelled_lymph_nodes=models.IntegerField(null=True)
    malaise=models.IntegerField(null=True)
    blurred_and_distorted_vision=models.IntegerField(null=True)
    phlegm=models.IntegerField(null=True)
    throat_irritation=models.IntegerField(null=True)
    redness_of_eyes=models.IntegerField(null=True)
    sinus_pressure=models.IntegerField(null=True)
    runny_nose=models.IntegerField(null=True)
    congestion=models.IntegerField(null=True)
    chest_pain=models.IntegerField(null=True)
    weakness_in_limbs=models.IntegerField(null=True)
    fast_heart_rate=models.IntegerField(null=True)
    pain_during_bowel_movements=models.IntegerField(null=True)
    pain_in_anal_region=models.IntegerField(null=True)
    bloody_stool=models.IntegerField(null=True)
    irritation_in_anus=models.IntegerField(null=True)
    neck_pain=models.IntegerField(null=True)
    dizziness=models.IntegerField(null=True)
    cramps=models.IntegerField(null=True)
    bruising=models.IntegerField(null=True)
    obesity=models.IntegerField(null=True)
    swollen_legs=models.IntegerField(null=True)
    swollen_blood_vessels=models.IntegerField(null=True)
    puffy_face_and_eyes=models.IntegerField(null=True)
    enlarged_thyroid=models.IntegerField(null=True)
    brittle_nails=models.IntegerField(null=True)
    swollen_extremeties=models.IntegerField(null=True)
    excessive_hunger=models.IntegerField(null=True)
    extra_marital_contacts=models.IntegerField(null=True)
    drying_and_tingling_lips=models.IntegerField(null=True)
    slurred_speech=models.IntegerField(null=True)
    knee_pain=models.IntegerField(null=True)
    hip_joint_pain=models.IntegerField(null=True)
    muscle_weakness=models.IntegerField(null=True)
    stiff_neck=models.IntegerField(null=True)
    swelling_joints=models.IntegerField(null=True)
    movement_stiffness=models.IntegerField(null=True)
    spinning_movements=models.IntegerField(null=True)
    loss_of_balance=models.IntegerField(null=True)
    unsteadiness=models.IntegerField(null=True)
    weakness_of_one_body_side=models.IntegerField(null=True)
    loss_of_smell=models.IntegerField(null=True)
    bladder_discomfort=models.IntegerField(null=True)
    #foul_smell_of_urine=models.IntegerField(null=True)
    continuous_feel_of_urine=models.IntegerField(null=True)
    passage_of_gases=models.IntegerField(null=True)
    internal_itching=models.IntegerField(null=True)
    #toxic_look_typhos=models.IntegerField(null=True)
    depression=models.IntegerField(null=True)
    irritability=models.IntegerField(null=True)
    muscle_pain=models.IntegerField(null=True)
    altered_sensorium=models.IntegerField(null=True)
    red_spots_over_body=models.IntegerField(null=True)
    belly_pain=models.IntegerField(null=True)
    abnormal_menstruation=models.IntegerField(null=True)
    #dischromic_patches=models.IntegerField(null=True)
    watering_from_eyes=models.IntegerField(null=True)
    increased_appetite=models.IntegerField(null=True)
    polyuria=models.IntegerField(null=True)
    family_history=models.IntegerField(null=True)
    mucoid_sputum=models.IntegerField(null=True)
    rusty_sputum=models.IntegerField(null=True)
    lack_of_concentration=models.IntegerField(null=True)
    visual_disturbances=models.IntegerField(null=True)
    receiving_blood_transfusion=models.IntegerField(null=True)
    receiving_unsterile_injections=models.IntegerField(null=True)
    coma=models.IntegerField(null=True)
    stomach_bleeding=models.IntegerField(null=True)
    distention_of_abdomen=models.IntegerField(null=True)
    history_of_alcohol_consumption=models.IntegerField(null=True)
    fluid_overload=models.IntegerField(null=True)
    blood_in_sputum=models.IntegerField(null=True)
    prominent_veins_on_calf=models.IntegerField(null=True)
    palpitations=models.IntegerField(null=True)
    painful_walking=models.IntegerField(null=True)
    pus_filled_pimples=models.IntegerField(null=True)
    blackheads=models.IntegerField(null=True)
    scurring=models.IntegerField(null=True)
    skin_peeling=models.IntegerField(null=True)
    silver_like_dusting=models.IntegerField(null=True)
    small_dents_in_nails=models.IntegerField(null=True)
    inflammatory_nails=models.IntegerField(null=True)
    blister=models.IntegerField(null=True)
    red_sore_around_nose=models.IntegerField(null=True)
    yellow_crust_ooze=models.IntegerField(null=True)
    prognosis=models.CharField(max_length=100)

class test(models.Model): 
    itching=models.IntegerField(null=True)
    skin_rash=models.IntegerField(null=True)
    nodal_skin_eruptions=models.IntegerField(null=True)
    continuous_sneezing=models.IntegerField(null=True)
    shivering=models.IntegerField(null=True)
    chills=models.IntegerField(null=True)
    joint_pain=models.IntegerField(null=True)
    stomach_pain=models.IntegerField(null=True)
    acidity=models.IntegerField(null=True)
    ulcers_on_tongue=models.IntegerField(null=True)
    muscle_wasting=models.IntegerField(null=True)
    vomiting=models.IntegerField(null=True)
    burning_micturition=models.IntegerField(null=True)
    #spotting_urination=models.IntegerField()
    fatigue=models.IntegerField(null=True)
    weight_gain=models.IntegerField(null=True)
    anxiety=models.IntegerField(null=True)
    cold_hands_and_feets=models.IntegerField(null=True)
    mood_swings=models.IntegerField(null=True)
    weight_loss=models.IntegerField(null=True)
    restlessness=models.IntegerField(null=True)
    lethargy=models.IntegerField(null=True)
    patches_in_throat=models.IntegerField(null=True)
    irregular_sugar_level=models.IntegerField(null=True)
    cough=models.IntegerField(null=True)
    high_fever=models.IntegerField(null=True)
    high_fever=models.IntegerField(null=True)
    sunken_eyes=models.IntegerField(null=True)
    breathlessness=models.IntegerField(null=True)
    sweating=models.IntegerField(null=True)
    dehydration=models.IntegerField(null=True)
    indigestion=models.IntegerField(null=True)
    headache=models.IntegerField(null=True)
    yellowish_skin=models.IntegerField(null=True)
    dark_urine=models.IntegerField(null=True)
    nausea=models.IntegerField(null=True)
    loss_of_appetite=models.IntegerField(null=True)
    pain_behind_the_eyes=models.IntegerField(null=True)
    back_pain=models.IntegerField(null=True)
    constipation=models.IntegerField(null=True)
    abdominal_pain=models.IntegerField(null=True)
    diarrhoea=models.IntegerField(null=True)
    mild_fever=models.IntegerField(null=True)
    mild_fever=models.IntegerField(null=True)
    yellowing_of_eyes=models.IntegerField(null=True)
    acute_liver_failure=models.IntegerField(null=True)
    fluid_overload=models.IntegerField(null=True)
    swelling_of_stomach=models.IntegerField(null=True)
    swelled_lymph_nodes=models.IntegerField(null=True)
    malaise=models.IntegerField(null=True)
    blurred_and_distorted_vision=models.IntegerField(null=True)
    phlegm=models.IntegerField(null=True)
    throat_irritation=models.IntegerField(null=True)
    redness_of_eyes=models.IntegerField(null=True)
    sinus_pressure=models.IntegerField(null=True)
    runny_nose=models.IntegerField(null=True)
    congestion=models.IntegerField(null=True)
    chest_pain=models.IntegerField(null=True)
    weakness_in_limbs=models.IntegerField(null=True)
    fast_heart_rate=models.IntegerField(null=True)
    pain_during_bowel_movements=models.IntegerField(null=True)
    pain_in_anal_region=models.IntegerField(null=True)
    bloody_stool=models.IntegerField(null=True)
    irritation_in_anus=models.IntegerField(null=True)
    neck_pain=models.IntegerField(null=True)
    dizziness=models.IntegerField(null=True)
    cramps=models.IntegerField(null=True)
    bruising=models.IntegerField(null=True)
    obesity=models.IntegerField(null=True)
    swollen_legs=models.IntegerField(null=True)
    swollen_blood_vessels=models.IntegerField(null=True)
    puffy_face_and_eyes=models.IntegerField(null=True)
    enlarged_thyroid=models.IntegerField(null=True)
    brittle_nails=models.IntegerField(null=True)
    swollen_extremeties=models.IntegerField(null=True)
    excessive_hunger=models.IntegerField(null=True)
    extra_marital_contacts=models.IntegerField(null=True)
    drying_and_tingling_lips=models.IntegerField(null=True)
    slurred_speech=models.IntegerField(null=True)
    knee_pain=models.IntegerField(null=True)
    hip_joint_pain=models.IntegerField(null=True)
    muscle_weakness=models.IntegerField(null=True)
    stiff_neck=models.IntegerField(null=True)
    swelling_joints=models.IntegerField(null=True)
    movement_stiffness=models.IntegerField(null=True)
    spinning_movements=models.IntegerField(null=True)
    loss_of_balance=models.IntegerField(null=True)
    unsteadiness=models.IntegerField(null=True)
    weakness_of_one_body_side=models.IntegerField(null=True)
    loss_of_smell=models.IntegerField(null=True)
    bladder_discomfort=models.IntegerField(null=True)
    #foul_smell_of_urine=models.IntegerField(null=True)
    continuous_feel_of_urine=models.IntegerField(null=True)
    passage_of_gases=models.IntegerField(null=True)
    internal_itching=models.IntegerField(null=True)
    #toxic_look_typhos=models.IntegerField(null=True)
    depression=models.IntegerField(null=True)
    irritability=models.IntegerField(null=True)
    muscle_pain=models.IntegerField(null=True)
    altered_sensorium=models.IntegerField(null=True)
    red_spots_over_body=models.IntegerField(null=True)
    belly_pain=models.IntegerField(null=True)
    abnormal_menstruation=models.IntegerField(null=True)
    #dischromic_patches=models.IntegerField(null=True)
    watering_from_eyes=models.IntegerField(null=True)
    increased_appetite=models.IntegerField(null=True)
    polyuria=models.IntegerField(null=True)
    family_history=models.IntegerField(null=True)
    mucoid_sputum=models.IntegerField(null=True)
    rusty_sputum=models.IntegerField(null=True)
    lack_of_concentration=models.IntegerField(null=True)
    visual_disturbances=models.IntegerField(null=True)
    receiving_blood_transfusion=models.IntegerField(null=True)
    receiving_unsterile_injections=models.IntegerField(null=True)
    coma=models.IntegerField(null=True)
    stomach_bleeding=models.IntegerField(null=True)
    distention_of_abdomen=models.IntegerField(null=True)
    history_of_alcohol_consumption=models.IntegerField(null=True)
    fluid_overload=models.IntegerField(null=True)
    blood_in_sputum=models.IntegerField(null=True)
    prominent_veins_on_calf=models.IntegerField(null=True)
    palpitations=models.IntegerField(null=True)
    painful_walking=models.IntegerField(null=True)
    pus_filled_pimples=models.IntegerField(null=True)
    blackheads=models.IntegerField(null=True)
    scurring=models.IntegerField(null=True)
    skin_peeling=models.IntegerField(null=True)
    silver_like_dusting=models.IntegerField(null=True)
    small_dents_in_nails=models.IntegerField(null=True)
    inflammatory_nails=models.IntegerField(null=True)
    blister=models.IntegerField(null=True)
    red_sore_around_nose=models.IntegerField(null=True)
    yellow_crust_ooze=models.IntegerField(null=True)
    prognosis=models.CharField(max_length=100)

class disease(models.Model):
    Disease=models.CharField(max_length=100)
    lines=models.CharField(max_length=100)
    image=models.URLField()
    pre_one=models.CharField(max_length=250)
    pre_two=models.CharField(max_length=250)
    pre_three=models.CharField(max_length=250)
    pre_four=models.CharField(max_length=250)
    detail=models.CharField(max_length=2000)

    
    def __str__(self):
        return self.Disease
class symptoms(models.Model):
    sym=models.CharField(max_length=250)

    def __str__(self):
        return self.sym

class medicines(models.Model):
    Disease=models.CharField(max_length=200)
    medicine=models.CharField(max_length=200)
    nutrient_1=models.CharField(max_length=200)
    Nutrient_2=models.CharField(max_length=200)
    food=models.CharField(max_length=200)
    lines=models.CharField(max_length=800)
    food=models.CharField(max_length=200,blank=True)
    doctors=models.CharField(max_length=200)
    doctors_two=models.CharField(max_length=200,blank=True)
    image_one=models.CharField(max_length=800)
    image_two=models.CharField(max_length=800)
    image_three=models.CharField(max_length=800)
    image_four=models.CharField(max_length=800)
    def __str__(self):
        return self.Disease
class doctorlogin(models.Model):
    doctor=models.CharField(max_length=200,blank=True)
    specialisation=models.CharField(max_length=200,blank=True)
    email=models.EmailField(max_length=200,blank=True)
    password=models.EmailField(max_length=200,blank=True)
    def __str__(self):
        return self.doctor
class Appoint(models.Model):
    user_name=models.CharField(max_length=200)
    email_patient=models.EmailField(max_length=50)
    doctor_name=models.CharField(max_length=100)
    doctor_email=models.EmailField(max_length=50)
    appointment_date=models.DateField()
    phone_number=models.CharField(max_length=15)
    address=models.CharField(max_length=300)
    patient_name=models.CharField(max_length=100)
    message=models.CharField(max_length=1000)
    age=models.IntegerField(default=0)
    
    
    time=models.CharField(default='',max_length=20)
    
    def __str__(self):
        return self.user_name

    




    
